const AllProjectsData = [
  {
    id: "projectNumber01",
    ProjectImgURl: "../GetURI.png",
    ProjectImgName: "Get URI",
    ProjectDesc:
      "Built for speed, efficiency, and ease of use. GetURI eliminates the complexity of media hosting so you can focus on what matters most—building amazing products.",
    ProjectImgCreatedAt: "20 JUNE 2025",
    ProjectUrlRedirectTo: "https://www.geturi.online",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "projectNumber02",
    ProjectImgURl: "../PersonaAEye.png",
    ProjectImgName: "PersonaAEye AI Project",
    ProjectDesc:
      "Developed using ReactJS, Zustand and  Tailwind CSS. Fully responsive design.",
    ProjectImgCreatedAt: "13 JUN 2025",
    ProjectUrlRedirectTo: "https://personaaeye.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200px",
  },
  {
    id: "projectNumber03",
    ProjectImgURl: "../PinsYourInterest1.png",
    ProjectImgName: "Pinterest Clone",
    ProjectDesc:
      "Developed using Node.js, Express.js, MongoDB, EJS, and Tailwind CSS. Fully responsive design.",
    ProjectImgCreatedAt: "10 JAN 2025",
    ProjectUrlRedirectTo: "https://pinsyourinterest.onrender.com",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200px",
  },
  {
    id: "projectNumber04",
    ProjectImgURl: "../ButtonJs.png",
    ProjectImgName: "Button JS",
    ProjectDesc:
      "Implemented with  React.js and Tailwind CSS. Fully responsive. Open Source Project to help bigginner's to contribute this project easily",
    ProjectImgCreatedAt: "11 AUG 2025",
    ProjectUrlRedirectTo: "https://buttonjs.vercel.app",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "projectNumber05",
    ProjectImgURl: "../ConstrutorWebsite.png",
    ProjectImgName: "Construction Website",
    ProjectDesc: "Built using HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 OCT 2023",
    ProjectUrlRedirectTo: "https://hmk-consutructionsdemo.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200%",
  },
  {
    id: "projectNumber06",
    ProjectImgURl: "../ColorPicker.jpeg",
    ProjectImgName: "Color Picker Tool",
    ProjectDesc:
      "Developed with HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 MAR 2024",
    ProjectUrlRedirectTo: "https://colors-hmk-codeweb.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "projectNumber07",
    ProjectImgURl: "../AnimationalPorfolio.jpeg",
    ProjectImgName: "Animated Portfolio",
    ProjectDesc:
      "Created using HTML5, Tailwind CSS, jQuery, and GSAP. Fully responsive with smooth animations.",
    ProjectImgCreatedAt: "3 JAN 2024",
    ProjectUrlRedirectTo: "https://hassaanhaider88portfolio.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200%",
  },
  {
    id: "projectNumber08",
    ProjectImgURl: "../FirstPorfolio.jpeg",
    ProjectImgName: "Portfolio V1",
    ProjectDesc: "Built with HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 AUG 2023",
    ProjectUrlRedirectTo: "https://hassaanhaider88.github.io/HMK_Portfolio/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "projectNumber09",
    ProjectImgURl: "../SonglessSongs.png",
    ProjectImgName: "Music App Clone",
    ProjectDesc:
      "Developed using HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 OCT 2024",
    ProjectUrlRedirectTo: "https://songless-songs.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "projectNumber10",
    ProjectImgURl: "../E_CommerceWeb.png",
    ProjectImgName: "E-Commerce Store",
    ProjectDesc:
      "Built with React.js, Tailwind CSS, JSX, and Context API. Fully responsive.",
    ProjectImgCreatedAt: "20 DEC 2023",
    ProjectUrlRedirectTo: "https://hmk-shop-by-hassaan-haider.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "projectNumber11",
    ProjectImgURl: "../DotGridDev.png",
    ProjectImgName: "Dot Grid Dev",
    ProjectDesc:
      "Created In Vanilla Js To Help Out Creation Of CSS Clip Path Shapes With ease",
    ProjectImgCreatedAt: "16 JUNE 2025",
    ProjectUrlRedirectTo: "https://dot-grid-dev.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "projectNumber12",
    ProjectImgURl: "../FoodEat.png",
    ProjectImgName: "FoodEat Resturant Web",
    ProjectDesc: "Built with HTML and  Tailwind CSS. Fully responsive.",
    ProjectImgCreatedAt: "20 JUNE 2025",
    ProjectUrlRedirectTo: "https://foodeat-by-hmk.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-150%",
  },
  {
    id: "projectNumber13",
    ProjectImgURl: "../Vs-CodeWeb.png",
    ProjectImgName: "Vs CodeWeb Editor",
    ProjectDesc:
      "Created In React And Monaco To Make VS Code Alternative Web Based Live Editor",
    ProjectImgCreatedAt: "23 JUNE 2025",
    ProjectUrlRedirectTo: "",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "projectNumber14",
    ProjectImgURl: "../Color-Picker.png",
    ProjectImgName: "Choose Thousand of Colors for Free",
    ProjectDesc: "Built with HTML and  Tailwind CSS. Fully responsive.",
    ProjectImgCreatedAt: "20 JUNE 2024",
    ProjectUrlRedirectTo: "https://vscodeweb1.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-100%",
  },
  {
    id: "projectNumber15",
    ProjectImgURl: "../BloggingSite.jpeg",
    ProjectImgName: "Blogging Platform",
    ProjectDesc:
      "Implemented with Next.js, React.js, Context API, Tailwind CSS, authentication, and authorization. Fully responsive.",
    ProjectImgCreatedAt: "20 FEB 2024",
    ProjectUrlRedirectTo: "https://hmk-codeweb.netlify.app",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
    {
    id: "projectNumber16",
    ProjectImgURl: "../CurrentPortfolio.jpeg",
    ProjectImgName: "Portfolio V3",
    ProjectDesc:
      "Crafted with HTML5, CSS3, JavaScript, and GSAP. Fully responsive and animated.",
    ProjectImgCreatedAt: "6 SEP 2023",
    ProjectUrlRedirectTo: "https://hmk-codeweb.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "20%",
  },
];

export default AllProjectsData;
