const AllProjectsData = [
  {
    id: "Zero",
    ProjectImgURl: "../GetURI.png",
    ProjectImgName: "Get URI",
    ProjectDesc:
      "Built for speed, efficiency, and ease of use. GetSrc eliminates the complexity of media hosting so you can focus on what matters most—building amazing products.",
    ProjectImgCreatedAt: "20 JUNE 2025",
    ProjectUrlRedirectTo: "",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },{
    id: "One",
    ProjectImgURl: "../PersonaAEye.png",
    ProjectImgName: "PersonaAEye AI Project",
    ProjectDesc:
      "Developed using ReactJS, Zustand and  Tailwind CSS. Fully responsive design.",
    ProjectImgCreatedAt: "13 JUN 2025",
    ProjectUrlRedirectTo: "https://personaaeye.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200px",
  },
  {
    id: "two",
    ProjectImgURl: "../PinsYourInterest1.png",
    ProjectImgName: "Pinterest Clone",
    ProjectDesc:
      "Developed using Node.js, Express.js, MongoDB, EJS, and Tailwind CSS. Fully responsive design.",
    ProjectImgCreatedAt: "10 JAN 2025",
    ProjectUrlRedirectTo: "https://pinsyourinterest.onrender.com",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200px",
  },
  {
    id: "three",
    ProjectImgURl: "../CurrentPortfolio.jpeg",
    ProjectImgName: "Portfolio V3",
    ProjectDesc:
      "Crafted with HTML5, CSS3, JavaScript, and GSAP. Fully responsive and animated.",
    ProjectImgCreatedAt: "6 SEP 2023",
    ProjectUrlRedirectTo: "https://hmk-codeweb.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200%",
  },
  // {
  //   id: "Four",
  //   ProjectImgURl: "../GetSrc.png",
  //   ProjectImgName: "Get Src",
  //   ProjectDesc:
  //     "Built for speed, efficiency, and ease of use. GetSrc eliminates the complexity of media hosting so you can focus on what matters most—building amazing products.",
  //   ProjectImgCreatedAt: "20 JUNE 2025",
  //   ProjectUrlRedirectTo: "",
  //   IconsDirection: "bottom-5 right-5",
  //   FlexDirecton: "flex-row",
  //   XVal: "-200%",
  // },
  {
    id: "Five",
    ProjectImgURl: "../ConstrutorWebsite.png",
    ProjectImgName: "Construction Website",
    ProjectDesc: "Built using HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 OCT 2023",
    ProjectUrlRedirectTo: "https://hmk-consutructionsdemo.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200%",
  },
  {
    id: "Six",
    ProjectImgURl: "../ColorPicker.jpeg",
    ProjectImgName: "Color Picker Tool",
    ProjectDesc:
      "Developed with HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 MAR 2024",
    ProjectUrlRedirectTo: "https://colors-hmk-codeweb.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "seven",
    ProjectImgURl: "../AnimationalPorfolio.jpeg",
    ProjectImgName: "Animated Portfolio",
    ProjectDesc:
      "Created using HTML5, Tailwind CSS, jQuery, and GSAP. Fully responsive with smooth animations.",
    ProjectImgCreatedAt: "3 JAN 2024",
    ProjectUrlRedirectTo: "https://hassaanhaider88portfolio.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "200%",
  },
  {
    id: "Eight",
    ProjectImgURl: "../FirstPorfolio.jpeg",
    ProjectImgName: "Portfolio V1",
    ProjectDesc: "Built with HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 AUG 2023",
    ProjectUrlRedirectTo: "https://hassaanhaider88.github.io/HMK_Portfolio/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "Nine",
    ProjectImgURl: "../SonglessSongs.png",
    ProjectImgName: "Music App Clone",
    ProjectDesc:
      "Developed using HTML5, CSS3, and JavaScript. Fully responsive.",
    ProjectImgCreatedAt: "2 OCT 2024",
    ProjectUrlRedirectTo: "https://songless-songs.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "Ten",
    ProjectImgURl: "../E_CommerceWeb.png",
    ProjectImgName: "E-Commerce Store",
    ProjectDesc:
      "Built with React.js, Tailwind CSS, JSX, and Context API. Fully responsive.",
    ProjectImgCreatedAt: "20 DEC 2023",
    ProjectUrlRedirectTo: "https://hmk-shop-by-hassaan-haider.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-200%",
  },
  {
    id: "Eleven",
    ProjectImgURl: "../DotGridDev.png",
    ProjectImgName: "Dot Grid Dev",
    ProjectDesc:
      "Created In Vanilla Js To Help Out Creation Of CSS Clip Path Shapes With ease",
    ProjectImgCreatedAt: "16 JUNE 2025",
    ProjectUrlRedirectTo: "https://dot-grid-dev.netlify.app/",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "Towelve",
    ProjectImgURl: "../FoodEat.png",
    ProjectImgName: "FoodEat Resturant Web",
    ProjectDesc: "Built with HTML and  Tailwind CSS. Fully responsive.",
    ProjectImgCreatedAt: "20 JUNE 2025",
    ProjectUrlRedirectTo: "https://foodeat-by-hmk.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-150%",
  },
  {
    id: "Therteen",
    ProjectImgURl: "../Vs-CodeWeb.png",
    ProjectImgName: "Vs CodeWeb Editor",
    ProjectDesc:
      "Created In React And Monaco To Make VS Code Alternative Web Based Live Editor",
    ProjectImgCreatedAt: "23 JUNE 2025",
    ProjectUrlRedirectTo: "",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
  {
    id: "Fourteen",
    ProjectImgURl: "../Color-Picker.png",
    ProjectImgName: "Choose Thousand of Colors for Free",
    ProjectDesc: "Built with HTML and  Tailwind CSS. Fully responsive.",
    ProjectImgCreatedAt: "20 JUNE 2024",
    ProjectUrlRedirectTo: "https://vscodeweb1.netlify.app/",
    IconsDirection: "bottom-5 right-5",
    FlexDirecton: "flex-row",
    XVal: "-100%",
  },
  {
    id: "FifTeen",
    ProjectImgURl: "../BloggingSite.jpeg",
    ProjectImgName: "Blogging Platform",
    ProjectDesc:
      "Implemented with Next.js, React.js, Context API, Tailwind CSS, authentication, and authorization. Fully responsive.",
    ProjectImgCreatedAt: "20 FEB 2024",
    ProjectUrlRedirectTo: "https://hmk-codeweb.netlify.app",
    IconsDirection: "bottom-5 left-5",
    FlexDirecton: "flex-row-reverse",
    XVal: "50%",
  },
];

export default AllProjectsData;
